runtime: python37

handlers:
  - url: /favicon\.ico
    static_files: kabloombox/static/images/favicons/favicon.ico
    upload: kabloombox/static/images/favicons/favicon\.ico
  - url: /.*
    script: auto
# error_handlers:
#   - file: templates/error.html
#     expiration: '1s'
